"""Registry of generated tools."""

from __future__ import annotations
from typing import List, Dict, Any
from ...core.memory_types import ToolSpec

class ToolMemoryLayer:
    """Stores custom tools generated by the optimizer."""
    
    def __init__(self, agent_id: str, config):
        self.tools: Dict[str, ToolSpec] = {}
    
    async def register_tool(self, tool: ToolSpec):
        self.tools[tool.name] = tool
    
    async def get_tool(self, name: str) -> ToolSpec:
        return self.tools.get(name)
