"""Pydantic Data Models for Polyglot DAG System."""

from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional
import uuid
from dataclasses import dataclass


class DAGNode(BaseModel):
    """Represents a single node in the polyglot DAG."""
    node_id: str = Field(default_factory=lambda: f"n_{uuid.uuid4().hex[:8]}")
    name: str
    runtime: str  # BASH, PYTHON, LLM, CLI_TOOL, HITL, SUBGRAPH
    payload: str  # Script, code, or prompt template
    input_mapping: Dict[str, str] = {}  # parent_node_id → local_var
    output_schema: Dict[str, Any] = {}
    timeout_ms: int = 5000
    retry_policy: Dict[str, Any] = {"max_retries": 0, "backoff_ms": 500}
    fusion_candidates: List[str] = []  # Sequential nodes merged here
    
    class Config:
        json_encoders = {
            dict: lambda v: v
        }


class DAGEdge(BaseModel):
    """Represents an edge between two nodes in the DAG."""
    source_id: str
    target_id: str
    condition: Optional[str] = None  # Python/bash boolean expression


class WorkflowDAG(BaseModel):
    """Complete workflow represented as a Directed Acyclic Graph."""
    dag_id: str = Field(default_factory=lambda: f"dag_{uuid.uuid4().hex[:8]}")
    version: int = 1
    name: str
    description: str
    nodes: List[DAGNode]
    edges: List[DAGEdge]
    maturation_layer: int = 1  # 1-4
    parallel_groups: List[List[str]] = []  # Pre-computed waves
    
    def get_node_by_id(self, node_id: str) -> Optional[DAGNode]:
        """Retrieve a node by its ID."""
        for node in self.nodes:
            if node.node_id == node_id:
                return node
        return None
    
    def get_parent_nodes(self, node_id: str) -> List[DAGNode]:
        """Get all parent nodes of a given node."""
        parents = []
        for edge in self.edges:
            if edge.target_id == node_id:
                parent = self.get_node_by_id(edge.source_id)
                if parent:
                    parents.append(parent)
        return parents


class WeaknessReport(BaseModel):
    """Report generated by Pessimistic Weakness Analyzer."""
    dag_id: str
    node_id: str
    fragility_score: float
    primary_cause: str  # BOTTLENECK, INSTABILITY, COST_BURN, LOW_DETERMINISM
    remediation: str    # e.g., "Merge with node_X", "Downgrade to jq", "Add retry"
    confidence: float


@dataclass
class NodeTelemetry:
    """Telemetry data collected per node execution."""
    node_id: str
    p50_ms: float
    p95_ms: float
    variance_ms: float          # Instability metric (p95 - p50)
    error_rate: float           # % failures in last 100 runs
    determinism_score: float    # 1.0 = identical output for same input
    tokens_used: int
    cost_usd: float
    cpu_peak_mb: float
    
    @classmethod
    def from_execution_logs(cls, node_id: str, logs: List[Dict[str, Any]]) -> 'NodeTelemetry':
        """Create telemetry from execution logs."""
        if not logs:
            return cls(
                node_id=node_id,
                p50_ms=0.0,
                p95_ms=0.0,
                variance_ms=0.0,
                error_rate=0.0,
                determinism_score=1.0,
                tokens_used=0,
                cost_usd=0.0,
                cpu_peak_mb=0.0
            )
        
        latencies = sorted([log.get('latency_ms', 0) for log in logs if log.get('success', False)])
        if not latencies:
            latencies = [0]
        
        p50_idx = int(len(latencies) * 0.5)
        p95_idx = int(len(latencies) * 0.95)
        
        p50 = latencies[p50_idx] if latencies else 0
        p95 = latencies[min(p95_idx, len(latencies) - 1)] if latencies else 0
        
        total_runs = len(logs)
        failed_runs = sum(1 for log in logs if not log.get('success', True))
        error_rate = failed_runs / total_runs if total_runs > 0 else 0
        
        # Calculate determinism (simplified: check output hash consistency)
        outputs = [log.get('output_hash') for log in logs if log.get('output_hash')]
        if outputs:
            unique_outputs = len(set(outputs))
            determinism = 1.0 / unique_outputs if unique_outputs > 0 else 1.0
        else:
            determinism = 1.0
        
        tokens = sum(log.get('tokens_used', 0) for log in logs)
        cost = sum(log.get('cost_usd', 0) for log in logs)
        cpu_peaks = [log.get('cpu_mb', 0) for log in logs if log.get('cpu_mb')]
        cpu_peak = max(cpu_peaks) if cpu_peaks else 0
        
        return cls(
            node_id=node_id,
            p50_ms=float(p50),
            p95_ms=float(p95),
            variance_ms=float(p95 - p50),
            error_rate=error_rate,
            determinism_score=determinism,
            tokens_used=tokens,
            cost_usd=cost,
            cpu_peak_mb=float(cpu_peak)
        )


class ExecutionTrace(BaseModel):
    """Historical execution trace for memory-driven optimization."""
    trace_id: str = Field(default_factory=lambda: f"trace_{uuid.uuid4().hex[:8]}")
    dag_id: str
    node_id: str
    node_type: str
    input_hash: str
    output_hash: Optional[str]
    telemetry: Dict[str, Any]
    error_trace: Optional[str]
    timestamp: float = Field(default_factory=lambda: __import__('time').time())
    
    class Config:
        json_encoders = {
            dict: lambda v: v
        }
